### ISSUE TITLE
不能使用ConstraintLayout布局

### ISSUE THREAD

**Issue by AlistairLi** [luckybilly/Gloading#11]
如果指定的view的父布局是 ConstraintLayout，其中的LayoutParams不是继承ViewGroup.LayoutParams，会报如下错误：
 java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.constraint.ConstraintLayout$LayoutParams

**Comment by AlistairLi** [comment]
sorry，我看了源码，都是继承ViewGroup.LayoutParams，但是，为什么报这个错误：
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.constraint.ConstraintLayout$LayoutParams

**Comment by luckybilly** [comment]
wrap(view)之后，使用holder.getWrapper()代替view添加到父控件
