### ISSUE TITLE
指定viewgroup显示不知道怎么用

### ISSUE THREAD

**Issue by qkun0715** [luckybilly/Gloading#12]

**Comment by luckybilly** [comment]
你说的是将LoadingView显示到指定的ViewGroup中并覆盖在所有子View之上吗？此功能在Gloading中暂未支持。

原因是：

指定ViewGroup显示存在一些限制，很多ViewGroup不支持覆盖在其它子view的上层，例如：LinearLayout

如果只支持RelativeLayout等个别ViewGroup的话，用户理解起来要多绕个弯，增加了框架的学习理解成本，而且也不能支持到用户自定义的ViewGroup。

**Comment by luckybilly** [comment]
@qkun0715 
如果你确实有这方面的需求，要实现也很简单：
1. copy Gloading.java到你的项目
2. 在Gloading.java中仿照wrap(activity)方法，创建一个wrap(ViewGroup viewGroup)方法
3. 在wrap(ViewGroup viewGroup)方法中根据支持的ViewGroup类型来进行支持
4. 调用Gloading.wrap(viewGroup)即可
