### ISSUE TITLE
使用中发现的问题

### ISSUE THREAD

**Issue by bux-git** [luckybilly/Gloading#14]
1.不断的对同一个Holder使用 Holder.showLoadingStatus() 会不断的嵌套状态view 因该通一状态的话 不需要去执行新增操作了
2.高度父ViewGroup 为wrap_content  子View为match_parent时，在子View位置显示状态View时 会让高度变成占满屏幕

**Comment by luckybilly** [comment]
@bux-git 
1. holder. showLoadingStatus(status)方法中会[将加载状态的view传给Adapter](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/gloading/src/main/java/com/billy/android/loading/Gloading.java#L214)，由Adapter来决定是否复用，请参考[demo](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/app/src/main/java/com/billy/android/loadingstatusview/wrapactivity/adapter/GlobalAdapter.java#L22)

2. 麻烦贴一下示例代码

**Comment by bux-git** [comment]
@luckybilly 不好意思哈 我这边代码有一些问题

**Comment by luckybilly** [comment]
@bux-git 没关系，有兴趣的话也欢迎关注我的[其它开源项目](https://github.com/luckybilly)
