### ISSUE TITLE
fragment复杂布局中不能单独覆盖某个view么？

### ISSUE THREAD

**Issue by cuixipeng** [luckybilly/Gloading#17]
我fragment中return view； 的话，就不会显示，如果return holder.getwarrp();的话 整个fragment就会被gloading覆盖

**Comment by luckybilly** [comment]
wrap的是哪个view就覆盖哪个view：
1. 你如果wrap的是根布局，那么就是整个fragment被覆盖（同时需要`return holder.getWrapper()`）
2. 如果你wrap的是根布局下面的某个view，那么覆盖的就只是那个子view的范围（不需要`return holder.getWrapper()`）

**Comment by cuixipeng** [comment]
当recyclerview 嵌套下拉加载的话第三方SmartRefreshLayout之后， gloading就显示空白了 就不显示了  ，这种情况就冲突了

**Comment by luckybilly** [comment]
参考 #22

**Comment by marren06** [comment]
把SmartRefreshLayout 当成一个单独的view为什么不行，showEmpty 是空白页面  但是loading 可以显示
