### ISSUE TITLE
配合RecycleView使用，数据加载成功，但为空调用showEmpty()方法后，接口请求方法不执行了

### ISSUE THREAD

**Issue by V-Beyond** [luckybilly/Gloading#18]
配合RecycleView使用，数据加载成功，但为空调用showEmpty()方法后，接口请求方法不执行了

**Comment by luckybilly** [comment]
接口请求方法不执行了指的是什么意思？你想要执行什么接口请求方法？

**Comment by V-Beyond** [comment]
现在问题是这样的：
进入列表首先调用LRecyclerView的下拉刷新方法去请求api接口，当请求成功后调用showEmpty来显示没有数据的状态，再次调用LRecyclerView的下拉刷新方法去请求api接口，结果api接口不执行了，如果直接请求api接口的话就正常。

**Comment by luckybilly** [comment]
难道你不是在下拉刷新的回调里面发起网络请求api吗？ onRefresh方法执行到了吗？
下拉刷新的UI效果展示了吗？

**Comment by V-Beyond** [comment]
已经解决
