### ISSUE TITLE
错误提示，空提示等，在想设置的activity和fragment里怎么动态设置呢

### ISSUE THREAD

**Issue by AndMy** [luckybilly/Gloading#19]
错误提示，空提示等，在想设置的activity和fragment里怎么动态设置呢
刚上手，还请解答下，我理解的是只要空页面的提示语，有变动，就得重新搞一个adapter？

**Comment by luckybilly** [comment]
不用重新弄Adapter
只有当UI样式不同时才需要定义多个，比如：
- 页面级UI样式定义一个Adapter
- item级是另一种UI样式，可另外定义一个Adapter

当UI相同但不同页面有局部细微差异时，可以通过[holder.withData(obj)](https://qibilly.com/Gloading/com/billy/android/loading/Gloading.Holder.html#withData-java.lang.Object-)来添加参数（比如存储不同状态下提示文字的Map），在[Adapter.getView方法](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/gloading/src/main/java/com/billy/android/loading/Gloading.java#L55)里，通过`holder.getData()`取出参数，根据status确定当前状态View要显示的文字并显示在view上。demo: [holder.withData(obj)](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/app/src/main/java/com/billy/android/loadingstatusview/wrapview/WrapRecyclerViewItemActivity.java#L83)、[holder.getData()](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/app/src/main/java/com/billy/android/loadingstatusview/wrapactivity/adapter/GlobalAdapter.java#L29)

**Comment by AndMy** [comment]
好的，了解了，感谢感谢
