### ISSUE TITLE
我在fragment中使用怎么不显示呀？求帮助

### ISSUE THREAD

**Issue by mxdlsm** [luckybilly/Gloading#20]

**Comment by luckybilly** [comment]
如果是为整个fragment显示加载状态，用`holder.getWrapper()`代替rootView。 [demo](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/app/src/main/java/com/billy/android/loadingstatusview/wrapfragment/WrapRootViewFragment.java#L48)
