### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by zzm123456** [luckybilly/Gloading#27]
### 

    
![1164379977f9348ba0e5de7c09ef056](https://user-images.githubusercontent.com/13730768/60854641-964a6300-a233-11e9-959c-eb8469a792e1.jpg)
public class GlobalAdapter implements Gloading.Adapter {
    private TextView mTvHint;

    @Override
    public View getView(Gloading.Holder holder, View convertView, int status) {
        GlobalLoadingStatusView loadingStatusView = null;
        //convertView为可重用的布局
        //Holder中缓存了各状态下对应的View
        //	如果status对应的View为null，则convertView为上一个状态的View
        //	如果上一个状态的View也为null，则convertView为null
        if (convertView != null && convertView instanceof GlobalLoadingStatusView) {
            loadingStatusView = (GlobalLoadingStatusView) convertView;
        }
        if (loadingStatusView == null) {
            loadingStatusView = new GlobalLoadingStatusView(holder.getContext(), holder.getRetryTask());
        }
        loadingStatusView.setStatus(status);
        return loadingStatusView;
    }

    class GlobalLoadingStatusView extends LinearLayout implements View.OnClickListener {

        private final Runnable mRetryTask;

        public GlobalLoadingStatusView(Context context, Runnable retryTask) {
            super(context);
            this.mRetryTask = retryTask;
            LayoutInflater.from(context).inflate(R.layout.view_loading_status, this, true);
            mTvHint = findViewById(R.id.tvHint);

            //初始化LoadingView
            //如果需要支持点击重试，在适当的时机给对应的控件添加点击事件
        }

        public void setStatus(int status) {
            //设置当前的加载状态：加载中、加载失败、空数据等
            //其中，加载失败可判断当前是否联网，可现实无网络的状态
            //		属于加载失败状态下的一个分支,可自行决定是否实现
            boolean show = true;
            View.OnClickListener onClickListener = null;
            switch (status) {
                case STATUS_LOAD_SUCCESS:
                    show = false;
                    mTvHint.setText("网络错误，触摸重新加载");
                    break;
                case STATUS_LOADING:
                    mTvHint.setText("加载中...");
                    break;
                case STATUS_LOAD_FAILED:
                    onClickListener = this;
                    mTvHint.setText("网络错误，触摸重新加载");
                    break;
                case STATUS_EMPTY_DATA:
                    break;
                default: break;
            }
            setOnClickListener(onClickListener);
            setVisibility(show ? View.VISIBLE : View.GONE);
        }

        @Override
        public void onClick(View v) {
            if (mRetryTask != null) {
                mRetryTask.run();
            }
        }
    }
}

**Comment by luckybilly** [comment]
@zzm123456 把`private TextView mTvHint;`移动到`GlobalLoadingStatusView`里面去吧

GlobalAdapter用作全局使用时，是为全局所有用到loading的地方所共用的，在Gloading中是用静态变量引用它的。请保持GlobalAdapter为无状态

**Comment by zzm123456** [comment]
谢谢回复，是我的疏忽 不好意思
