### ISSUE TITLE
共7个问题，使用该库的一些思考……

### ISSUE THREAD

**Issue by yangchong211** [luckybilly/Gloading#29]
1.如果用于activity或者fragment中，则不同的页面是否可以动态设置不同状态的空页面，感觉该项目不太方便。
2.针对空界面或者异常状态视图，感觉可以用ViewStub替代，当需要的时候在inflate出来。
3.如果是recyclerView中复杂布局而不是imageView，感觉状态还是不太友好管理。
4.如果页面需要定制不同的空数据状态，则要写多个样式的adapter，感觉有点麻烦，如果是后期将不同状态set进去就好了。
5.在recyclerView中，当item数据，比如前10条还在加载loading，从可见到不可见，有些状态切换为加载失败。然后滑动加载后面的数据，当再次回到前10条数据，则会又重新loading
6.比如有些页面，我只想设置状态页面有加载正式视图和失败视图，则这个库不太好处理。
7.给状态页面设置点击事件，比如异常界面出现后，我想点击重试加载数据，用在activity中，能否把监听暴露出来让开发者自己实现
8.大神这个库特别好，我可以引用到我的状态管理器库中么，刚好可以弥补我的问题。
状态管理器：https://github.com/yangchong211/YCStateLayout
要是可以，大神能推荐一下就好了，谢谢！

**Comment by luckybilly** [comment]
hi, @yangchong211  很高兴你关注到Gloading项目，你提的问题很多，我就采取一一对应的方式来回答你吧：

> 1. 如果用于activity或者fragment中，则不同的页面是否可以动态设置不同状态的空页面，感觉该项目不太方便。

Gloading是基于Adapter模式来提供状态view的，支持全局统一状态view和个别页面[显示特殊状态view](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/app/src/main/java/com/billy/android/loadingstatusview/wrapactivity/SpecialActivity.java#L20)。而且，重要的是：gloading对状态view没有任何限制，可以是一个简单的布局，也可以是一个非常复杂的自定义view，从而能支持使用各种炫酷的第三方动画作为加载动画

一般来说，同一个app内的加载动画应该是全局统一的，有利于保持统一风格（当然不排除有个别页面需要一些特殊效果），特殊的加载状态应该不会很多。

另外，Gloading库的核心目的是进行解耦。特别是在组件化环境下，某些页面会在不同的app之间复用（例如：WebFragment、WeexFragment等），如果加载状态view耦合进页面布局中，将不利于它们在不同app之间的复用

---

> 2.针对空界面或者异常状态视图，感觉可以用ViewStub替代，当需要的时候在inflate出来。

Gloading调用`adapter.getView`时才会创建状态view并添加到布局上，而`adapter.getView`是在调用`holder.showLoadingStatus(status)`显示加载状态时才会调用。

并且同一时间最多只有一个状态view会被添加到布局中。

**所以：Gloading中无需ViewStub方案**

---

> 3.如果是recyclerView中复杂布局而不是imageView，感觉状态还是不太友好管理。

Gloading的实现原理是创建一个frameLayout来包裹需要显示加载状态的控件，跟它的类型没有关系

---

> 4.如果页面需要定制不同的空数据状态，则要写多个样式的adapter，感觉有点麻烦，如果是后期将不同状态set进去就好了。

Gloading提供了`holder.withData(obj)`设置附加信息，在`adapter.getView(holder, view, statue)`方法内可以根据`holder.getData()`取出当前holder中的附加信息，再结合当前的status参数，可以用同一个adapter来显示不同的布局。

*这种方式对于不同页面空数据状态的提示文字不同等局部细微差异非常合适*

---

> 5.在recyclerView中，当item数据，比如前10条还在加载loading，从可见到不可见，有些状态切换为加载失败。然后滑动加载后面的数据，当再次回到前10条数据，则会又重新loading

在Gloding的demo中可以复现这个现象，不过这不是Gloading的问题，**Gloading只负责显示加载状态，至于要显示什么状态，由调用处来决定**。

demo中的用法是：在`ViewHolder.showImage(String url)`中先显示loading状态，再加载图片。由于有2张图片的地址错误，Glide加载不出来图片，也就没有缓存，每次会尝试重新加载，所以会显示一下loading状态。 详见[demo代码](https://github.com/luckybilly/Gloading/blob/150b6dc90bd6ab989a299fb80b314cea7745f1be/app/src/main/java/com/billy/android/loadingstatusview/wrapview/WrapRecyclerViewItemActivity.java#L113)

---

> 6.比如有些页面，我只想设置状态页面有加载正式视图和失败视图，则这个库不太好处理。

每种状态的显示与否，取决于`holder.showLoadingStatus(status)`的status参数。
如果只需要正式视图和失败视图，可以调用`holder.showLoadFailed()`显示失败状态，调用`holder.showLoadSuccess()`显示正式状态即可。

另外：如果将Gloading的使用封装到BaseActivity/BaseFragment中，例如[demo中的BaseActivity](https://github.com/luckybilly/Gloading/blob/master/app/src/main/java/com/billy/android/loadingstatusview/BaseActivity.java)， 可以在子类中复写对应的方法来屏蔽你想要在当前页面中禁用的状态显示。

---

> 7.给状态页面设置点击事件，比如异常界面出现后，我想点击重试加载数据，用在activity中，能否把监听暴露出来让开发者自己实现

`holder.withRetryTask(task)`设置的就是开发者定义的失败重试逻辑。

不过，为了减少框架侵入性，这个task是Runnable类型的，没有新增额外的回调接口

---

> 8.大神这个库特别好，我可以引用到我的状态管理器库中么，刚好可以弥补我的问题。
> 状态管理器：https://github.com/yangchong211/YCStateLayout

完全可以啊，我已经开源出来了，如果你是通过maven依赖使用，完全没问题；如果是直接复制修改源码，按照Apache-2.0开源协议注明来源即可。

---

> 要是可以，大神能推荐一下就好了，谢谢！

YCStateLayout封装的挺好的，而且是2年前就已经开源了的，很赞！
