### ISSUE TITLE
如果fragment的根布局是相对布局或者约束布局会报错

### ISSUE THREAD

**Issue by yxyaxng** [luckybilly/Gloading#34]
![image](https://user-images.githubusercontent.com/24906252/74584037-a8318700-5008-11ea-8b70-07060ab13ff3.png)

**Comment by luckybilly** [comment]
@yxyaxng 为RelativeLayout或ConstraintLayout **内部的某个子view** 显示loadingView时用`cover`，其它情况下用`wrap`

如果是为fragment的根布局显示loadingView，请使用`wrap`
