### ISSUE TITLE
使用Fragment+viewpage，发现虽说看不见底部布局，但是点击事件都还在

### ISSUE THREAD

**Issue by Alexxiaopang** [luckybilly/Gloading#35]
使用Fragment+viewpage，发现虽说看不见底部布局，但是点击事件都还在
比如屏幕A点有点击事件，这时候错误view把A盖住了，但是点击A的位置，点击事件都还在

**Comment by luckybilly** [comment]
@Alexxiaopang 这是FrameLayout的点击穿透问题，可在LoadingView设置`android:clickable="true" `或`loadingView.setClickable(true)`

Gloading使用FrameLayout将目标view包裹起来，并将LoadingView显示在最上层，Gloading本身并未对LoadingView进行额外的属性设置，如果不想点击穿透，请`设置LoadingView的clickable为true `

**Comment by Alexxiaopang** [comment]
好的，谢谢
