### ISSUE TITLE
不支持动态修改text和image的内容吗

### ISSUE THREAD

**Issue by ltym2016** [luckybilly/Gloading#4]

**Comment by luckybilly** [comment]
1. 创建Holder时，通过`holder.widthData(Object data) `来传递参数
2. 创建LoadingView时，在`Adapter.getView(holder, convertView, status)`方法中，通过`holder.getData()`来获取参数，可以根据参数来创建View，文字、图片等UI内容可根据data来确定。
@ltym2016
