### ISSUE TITLE
Fragment与ViewPager结合使用的问题

### ISSUE THREAD

**Issue by HQLIE2018** [luckybilly/Gloading#5]
Fragment与ViewPager结合使用，当滑动到未加载的第二页时，会先出现内容视图，然后才会出现加载的页面，ViewPager调用了setOffscreenPageLimit这个方法，会不会跟调用了这个方法有关？

**Comment by luckybilly** [comment]
加载中的状态是在调用`holder. showLoading();`时显示的，请检查一下你是在何时调用的

**Comment by HQLIE2018** [comment]
在setUserVisibleHint这个方法里，当Fragment可见时调用

**Comment by luckybilly** [comment]
不清楚你的具体业务逻辑，不过作为尝试，你将它提前到onCreateView或者onViewCreated中调用试试

**Comment by luckybilly** [comment]
[demo](https://github.com/luckybilly/Gloading/blob/a213c1f88f0f8d3a477debe84c1147243d178d05/app/src/main/java/com/billy/android/loadingstatusview/wrapfragment/WrapRootViewFragment.java#L47)

**Comment by HQLIE2018** [comment]
其实就是ViewPager滑动到下一个Fragment时，在setUserVisibleHint(boolean isVisibleToUser)这个方法里面做了一个懒加载操作

**Comment by HQLIE2018** [comment]
大概知道什么原因了，谢谢！
