### ISSUE TITLE
把button交给gloading时，不起效果

### ISSUE THREAD

**Issue by alguojian** [luckybilly/Gloading#8]
wrap的是一个button，不起效果，其他的view都是可以的

        View rootView = inflater.inflate(R.layout.fragment_blank, container, false);
        holder = Gloading.getDefault().wrap(rootView.findViewById(R.id.bbb)).withRetry(new Runnable() {
            @Override
            public void run() {

            }
        });

**Comment by luckybilly** [comment]
确实存在这样的问题：android L（5.0）新增了Elevation的概念，正好Button在5.0以后的默认阴影动画效果使用了elevation，所以不仅仅是Button有问题，而是设置了elevation的view都会遇到这个问题，感谢你的提醒。
参考资料：
1. [button_state_list_anim_material.xml](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/anim/button_state_list_anim_material.xml#39)
2. [dimens_material.xml](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/dimens_material.xml#103)

解决办法：
1. 去除Button的动画效果（不推荐）
```xml
<Button
    ...
    android:stateListAnimator="@null" />
```
2. 在Adapter中给LoadingView设置更高的elevation
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    loadingStatusView.setElevation(Float.MAX_VALUE);
}
```
3. 升级Gloading版本1.0.1版 (**推荐**）

**Comment by alguojian** [comment]
好的，辛苦了
